---
kind: pipeline
name: testing-windows

platform:
  os: windows
  arch: amd64
  version: 1809

clone:
  disable: true

steps:

- name: docker
  pull: always
  image: plugins/docker
  settings:
    daemon_off: true
    dry_run: true
    dockerfile: docker/Dockerfile.windows.1809
    repo: test/test
    tags: latest
    purge: false
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

volumes:
- name: docker_pipe
  host:
    path: \\\\.\\pipe\\docker_engine

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"
  - "refs/pull/**"
...
