---
kind: pipeline
name: testing-linux

platform:
  os: linux
  arch: amd64

steps:
- name: vet
  pull: always
  image: golang:1.11
  commands:
  - ls

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"
  - "refs/pull/**"
---
kind: pipeline
name: testing-windows

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
- name: docker  
  pull: always
  image: plugins/docker:windows-1809
  settings:
    daemon_off: true
    dockerfile: docker/Dockerfile.windows.1809
    username: loganhz
    password: zhanghao
    repo: loganhz/test
    tags: latest
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

volumes:
- name: docker_pipe
  host:
    path: \\\\.\\pipe\\docker_engine

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"
  - "refs/pull/**"
...