---
kind: pipeline
name: testing-linux

platform:
  os: linux
  arch: amd64

steps:
- name: vet
  pull: always
  image: golang:1.11
  commands:
  - ls

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"
  - "refs/pull/**"
---
kind: pipeline
name: testing-windows

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
- name: vet
  pull: always
  image: plugins/docker:windows-1809
  commands:
  - ls

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"
  - "refs/pull/**"
...