---
kind: pipeline
name: testing-windows

platform:
  os: windows
  arch: amd64
  version: 1809

clone:
  disable: true

steps:

- name: clone
  image: tayworm/drone-git:latest
  environment:
    GIT_AUTHOR_NAME: test
    GIT_AUTHOR_EMAIL: test@test.com

- name: docker
  pull: always
  image: plugins/docker:windows-1809
  settings:
    daemon_off: true
    dry_run: true
    context: ""
    dockerfile: docker/Dockerfile.windows.1809
    repo: test/test
    tags: latest
    pull_image: "false"
    purge: "false"
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine

volumes:
- name: docker_pipe
  host:
    path: \\\\.\\pipe\\docker_engine

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"
  - "refs/pull/**"
...
