apiVersion: v1
kind: ConfigMap
metadata:
  name: rancher-config
  labels: {{ include "rancher.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: "rancher"
data:
  priorityClassName:  {{ .Values.priorityClassName }}
  {{- if and .Values.webhook (kindIs "string" .Values.webhook) }}
  rancher-webhook: {{  .Values.webhook | nindent 4 | squote }}
  {{- else if .Values.webhook }}
  rancher-webhook: {{ toYaml .Values.webhook | nindent 4 | squote }}
  {{- end }}
