apiVersion: v1
kind: Secret
metadata:
  name: "bootstrap-secret"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace "bootstrap-secret" }}
  {{- if $existingSecret }}
  bootstrapPassword: {{ $existingSecret.data.bootstrapPassword }}
  {{- else }}
  bootstrapPassword: {{ .Values.bootstrapPassword | b64enc | quote }}
  {{- end }}