{{- /* Create the secret only if we set the value and the value does not already exist */ -}}
{{- $exists := lookup "v1" "Secret" .Release.Namespace "bootstrap-secret" }}
{{- if and .Values.bootstrapPassword (not $exists) }}
apiVersion: v1
kind: Secret
metadata:
  name: "bootstrap-secret"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  bootstrapPassword: {{ .Values.bootstrapPassword | b64enc | quote }}
{{- end }}