apiVersion: v1
kind: Service
metadata:
  annotations:
    # Disable NEGs which use /healthz as the healthcheck by default
    # Avoids a lot of extra google centeric configuration
    cloud.google.com/neg: '{"ingress": false}'
  name: {{ template "rancher.fullname" . }}
  labels:
{{ include "rancher.labels" . | indent 4 }}
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 444
    protocol: TCP
    name: https-internal
  selector:
    app: {{ template "rancher.fullname" . }}
{{- if eq .Values.ingress.tls.source "google" -}}
  # Assumes a private cluster per best practices
  type: NodePort
{{- end }}
