apiVersion: v1
kind: Service
metadata:
  name: {{ template "rancher.fullname" . }}
  labels:
    app: {{ template "rancher.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
{{- if eq .Values.tls "internal" }}
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
{{- end }}
  selector:
    app: {{ template "rancher.fullname" . }}
