name: Final release actions

on:
  workflow_dispatch:
  pull_request:
      types:
      - opened
      - edited
      - synchronize

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  pre-check-pr:
    runs-on: ubuntu-latest
    steps:
      - id: check-step-id 
        name: validate pr title
        run: |
          PR_TITLE="${{ github.event.pull_request.title || '' }}"
          if [[ ! "$PR_TITLE" == *"PR FOR FINAL RC"* ]]; then
            echo "skipping..."
            echo "::set-output name=is-final-rc::true"
          fi
          echo "::set-output name=is-final-rc::false"   

  check-deps-and-tags:
    runs-on: ubuntu-latest
    needs: validate-pr-title
    if: needs.validate-pr-title.outputs.is-final-rc == 'true'
    steps:
      -
        uses: actions/checkout@v4
        if: success() 
        with:
          fetch-depth: 0
          ref: ${{ env.GITHUB_SHA }}
      - name: setup ecm-distro-tools
        uses: johnatasr/ecm-distro-tools@v0.25.2
        with:
          version: v0.25.2
      - name: check final rcs and dev dependencies
        run: |
          FILES=Dockerfile.dapper,go.mod,/package/Dockerfile,/pkg/apis/go.mod,/pkg/settings/setting.go,/scripts/package-env
          HASH_COMMIT=${{ env.GITHUB_SHA }}
          OS=$(uname -s)
          AR=$(uname -m)
          rancher_release-${OS,,}-${AR} check-rancher-rc-deps -p -c ${HASH_COMMIT} -f S{FILES}
